name: Build main target

on:
  pull_request:
    paths:
      - '.github/workflows/**'
      - CDMarkdownKit.xcodeproj/**
      - CDMarkdownKitTests/**
      - Source/**

    push:
      branches:
        - main
        - master
        - stable*

permissions:
  contents: read

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-15

    env:
      WORKSPACE: CDMarkdownKit.xcworkspace
      DESTINATION: platform=iOS Simulator,name=iPhone 16,OS=18.5
      SCHEME: "CDMarkdownKit iOS"

    steps:
    - name: Checkout app
      uses: actions/checkout@v3

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: '26.2'

    - name: Install iOS 18.5
      run: |
        xcrun simctl list > /dev/null # Required to prevent the next command from sometimes not working
        xcodebuild -downloadPlatform iOS -buildVersion 18.5

    - name: Build & Test CDMarkdownKit iOS
      run: |
        set -o pipefail && xcodebuild test -workspace $WORKSPACE \
        -scheme "$SCHEME" \
        -destination "$DESTINATION" \
        -test-iterations 3 \
        -retry-tests-on-failure \
        | xcpretty
